id = "aurora"
name = "Aurora"
version = "0.0.1"
schema_version = 1
authors = ["Enzo Innocenzi <zed@innocenzi.dev>"]
description = "Dark, warm theme with sunset hues and smooth contrast."
repository = "https://github.com/innocenzi/zed-theme-aurora"
